/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package firstgui;

/**
 *
 * @author tduwe
 */
public class TemperatureConverter extends javax.swing.JFrame {

    /**
     * Creates new form TemperatureConverter
     */
    public TemperatureConverter() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tmpFahr = new javax.swing.JLabel();
        textFahrenheit = new javax.swing.JTextField();
        buttonForCelcius = new javax.swing.JButton();
        textCelcius = new javax.swing.JTextField();
        buttonForFahrenheit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tmpFahr.setText("Enter Degrees in Fahrenheit");

        textFahrenheit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFahrenheitActionPerformed(evt);
            }
        });

        buttonForCelcius.setText("Convert to Celcius");
        buttonForCelcius.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonForCelciusActionPerformed(evt);
            }
        });

        textCelcius.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textCelciusActionPerformed(evt);
            }
        });

        buttonForFahrenheit.setText("Convert to Fahrenheit");
        buttonForFahrenheit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonForFahrenheitActionPerformed(evt);
            }
        });

        jLabel1.setText("Enter Degrees in Celcius");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(tmpFahr)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(textFahrenheit, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonForCelcius))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(textCelcius, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(buttonForFahrenheit))
                .addGap(0, 124, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tmpFahr)
                    .addComponent(textFahrenheit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textCelcius, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonForCelcius)
                    .addComponent(buttonForFahrenheit))
                .addContainerGap(191, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonForCelciusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonForCelciusActionPerformed
        // TODO add your handling code here:
        double temp = Double.parseDouble(textFahrenheit.getText());
        textCelcius.setText(String.valueOf((temp - 32) * 5 / 9));
    }//GEN-LAST:event_buttonForCelciusActionPerformed

    private void textCelciusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textCelciusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textCelciusActionPerformed

    private void textFahrenheitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFahrenheitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFahrenheitActionPerformed

    private void buttonForFahrenheitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonForFahrenheitActionPerformed
        // TODO add your handling code here:
        double temp = Double.parseDouble(textCelcius.getText());
        textFahrenheit.setText(String.valueOf(temp * 9 / 5 + 32));
    }//GEN-LAST:event_buttonForFahrenheitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonForCelcius;
    private javax.swing.JButton buttonForFahrenheit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField textCelcius;
    private javax.swing.JTextField textFahrenheit;
    private javax.swing.JLabel tmpFahr;
    // End of variables declaration//GEN-END:variables
}
